package com.eroom.web.entity.po;
// Generated 2017-5-24 16:38:21 by Hibernate Tools 5.2.1.Final

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * AccountBook generated by hbm2java
 */
@Entity
@Table(name = "t_account_book", catalog = "eroom")
public class AccountBook implements java.io.Serializable {

    private Long bookId;

    private long custId;

    private String bookItemId;

    private BigDecimal totalAmount;

    private BigDecimal paidAmount;

    private BigDecimal dueAmount;

    private BigDecimal payAmount;

    private BigDecimal freezeAmount;

    private String state;

    private Date createTime;

    private Date updateTime;

    public AccountBook() {
    }

    public AccountBook(long custId, String bookItemId, BigDecimal totalAmount,
                       BigDecimal paidAmount, BigDecimal dueAmount, BigDecimal payAmount,
                       BigDecimal freezeAmount, String state, Date createTime) {
        this.custId = custId;
        this.bookItemId = bookItemId;
        this.totalAmount = totalAmount;
        this.paidAmount = paidAmount;
        this.dueAmount = dueAmount;
        this.payAmount = payAmount;
        this.freezeAmount = freezeAmount;
        this.state = state;
        this.createTime = createTime;
    }

    public AccountBook(long custId, String bookItemId, BigDecimal totalAmount,
                       BigDecimal paidAmount, BigDecimal dueAmount, BigDecimal payAmount,
                       BigDecimal freezeAmount, String state, Date createTime, Date updateTime) {
        this.custId = custId;
        this.bookItemId = bookItemId;
        this.totalAmount = totalAmount;
        this.paidAmount = paidAmount;
        this.dueAmount = dueAmount;
        this.payAmount = payAmount;
        this.freezeAmount = freezeAmount;
        this.state = state;
        this.createTime = createTime;
        this.updateTime = updateTime;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "book_id", unique = true, nullable = false)
    public Long getBookId() {
        return this.bookId;
    }

    public void setBookId(Long bookId) {
        this.bookId = bookId;
    }

    @Column(name = "cust_id", nullable = false)
    public long getCustId() {
        return this.custId;
    }

    public void setCustId(long custId) {
        this.custId = custId;
    }

    @Column(name = "book_item_id", nullable = false, length = 4)
    public String getBookItemId() {
        return this.bookItemId;
    }

    public void setBookItemId(String bookItemId) {
        this.bookItemId = bookItemId;
    }

    @Column(name = "total_amount", nullable = false, precision = 10)
    public BigDecimal getTotalAmount() {
        return this.totalAmount;
    }

    public void setTotalAmount(BigDecimal totalAmount) {
        this.totalAmount = totalAmount;
    }

    @Column(name = "paid_amount", nullable = false, precision = 10)
    public BigDecimal getPaidAmount() {
        return this.paidAmount;
    }

    public void setPaidAmount(BigDecimal paidAmount) {
        this.paidAmount = paidAmount;
    }

    @Column(name = "due_amount", nullable = false, precision = 10)
    public BigDecimal getDueAmount() {
        return this.dueAmount;
    }

    public void setDueAmount(BigDecimal dueAmount) {
        this.dueAmount = dueAmount;
    }

    @Column(name = "pay_amount", nullable = false, precision = 10)
    public BigDecimal getPayAmount() {
        return this.payAmount;
    }

    public void setPayAmount(BigDecimal payAmount) {
        this.payAmount = payAmount;
    }

    @Column(name = "freeze_amount", nullable = false, precision = 10)
    public BigDecimal getFreezeAmount() {
        return this.freezeAmount;
    }

    public void setFreezeAmount(BigDecimal freezeAmount) {
        this.freezeAmount = freezeAmount;
    }

    @Column(name = "state", nullable = false, length = 4)
    public String getState() {
        return this.state;
    }

    public void setState(String state) {
        this.state = state;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "create_time", nullable = false, length = 19)
    public Date getCreateTime() {
        return this.createTime;
    }

    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "update_time", length = 19)
    public Date getUpdateTime() {
        return this.updateTime;
    }

    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

}
