package com.eroom.web.entity.po;
// Generated 2017-5-24 16:38:21 by Hibernate Tools 5.2.1.Final

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * AccountBookDetail generated by hbm2java
 */
@Entity
@Table(name = "account_book_detail", catalog = "eroom")
public class AccountBookDetail implements java.io.Serializable {

    private Long bookDetailId;

    private long custId;

    private long bookId;

    private String inOutFlag;

    private BigDecimal amount;

    private Date optTime;

    private String busiType;

    private String busiDesc;

    private String externalSeq;

    private String state;

    private String remark;

    private Date createTime;

    private Date updateTime;

    public AccountBookDetail() {
    }

    public AccountBookDetail(long custId, long bookId, String inOutFlag, BigDecimal amount,
                             Date optTime, String state, Date createTime) {
        this.custId = custId;
        this.bookId = bookId;
        this.inOutFlag = inOutFlag;
        this.amount = amount;
        this.optTime = optTime;
        this.state = state;
        this.createTime = createTime;
    }

    public AccountBookDetail(long custId, long bookId, String inOutFlag, BigDecimal amount,
                             Date optTime, String busiType, String busiDesc, String externalSeq, String state,
                             String remark, Date createTime, Date updateTime) {
        this.custId = custId;
        this.bookId = bookId;
        this.inOutFlag = inOutFlag;
        this.amount = amount;
        this.optTime = optTime;
        this.busiType = busiType;
        this.busiDesc = busiDesc;
        this.externalSeq = externalSeq;
        this.state = state;
        this.remark = remark;
        this.createTime = createTime;
        this.updateTime = updateTime;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "book_detail_id", unique = true, nullable = false)
    public Long getBookDetailId() {
        return this.bookDetailId;
    }

    public void setBookDetailId(Long bookDetailId) {
        this.bookDetailId = bookDetailId;
    }

    @Column(name = "cust_id", nullable = false)
    public long getCustId() {
        return this.custId;
    }

    public void setCustId(long custId) {
        this.custId = custId;
    }

    @Column(name = "book_id", nullable = false)
    public long getBookId() {
        return this.bookId;
    }

    public void setBookId(long bookId) {
        this.bookId = bookId;
    }

    @Column(name = "in_out_flag", nullable = false, length = 4)
    public String getInOutFlag() {
        return this.inOutFlag;
    }

    public void setInOutFlag(String inOutFlag) {
        this.inOutFlag = inOutFlag;
    }

    @Column(name = "amount", nullable = false, precision = 10)
    public BigDecimal getAmount() {
        return this.amount;
    }

    public void setAmount(BigDecimal amount) {
        this.amount = amount;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "opt_time", nullable = false, length = 19)
    public Date getOptTime() {
        return this.optTime;
    }

    public void setOptTime(Date optTime) {
        this.optTime = optTime;
    }

    @Column(name = "busi_type", length = 6)
    public String getBusiType() {
        return this.busiType;
    }

    public void setBusiType(String busiType) {
        this.busiType = busiType;
    }

    @Column(name = "busi_desc", length = 128)
    public String getBusiDesc() {
        return this.busiDesc;
    }

    public void setBusiDesc(String busiDesc) {
        this.busiDesc = busiDesc;
    }

    @Column(name = "external_seq", length = 32)
    public String getExternalSeq() {
        return this.externalSeq;
    }

    public void setExternalSeq(String externalSeq) {
        this.externalSeq = externalSeq;
    }

    @Column(name = "state", nullable = false, length = 4)
    public String getState() {
        return this.state;
    }

    public void setState(String state) {
        this.state = state;
    }

    @Column(name = "remark", length = 128)
    public String getRemark() {
        return this.remark;
    }

    public void setRemark(String remark) {
        this.remark = remark;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "create_time", nullable = false, length = 19)
    public Date getCreateTime() {
        return this.createTime;
    }

    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "update_time", length = 19)
    public Date getUpdateTime() {
        return this.updateTime;
    }

    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

}
