package com.eroom.web.entity.po;
// Generated 2017-5-24 16:38:21 by Hibernate Tools 5.2.1.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * CmCustWx generated by hbm2java
 */
@Entity
@Table(name = "cm_cust_wx", catalog = "eroom")
public class CmCustWx implements java.io.Serializable {

    private Long custId;

    private Long agentCustId;

    private String agentFlag;

    private String agentGroupNo;

    private String agentType;

    private String bindMobile;

    private Date createTime;

    private Date followTime;

    private String loginAcct;

    private String loginPwd;

    private String nickname;

    private String openid;

    private String qrCode;

    private String state;

    private String tenantNo;

    private Date updateTime;

    private Integer chnlType;

    private String headImgUrl;

    private String cardNo;

    private String custLevel;

    private String custName;

    private String headimgurl;

    private Date lastLoginTime;

    private Long totalFee;

    private String wechatNo;

    private String authFlag;

    public CmCustWx() {
    }

    public CmCustWx(String agentFlag, Date createTime, String state, String tenantNo,
            String authFlag) {
        this.agentFlag = agentFlag;
        this.createTime = createTime;
        this.state = state;
        this.tenantNo = tenantNo;
        this.authFlag = authFlag;
    }

    public CmCustWx(Long agentCustId, String agentFlag, String agentGroupNo, String agentType,
            String bindMobile, Date createTime, Date followTime, String loginAcct, String loginPwd,
            String nickname, String openid, String qrCode, String state, String tenantNo,
            Date updateTime, Integer chnlType, String headImgUrl, String cardNo, String custLevel,
            String custName, String headimgurl, Date lastLoginTime, Long totalFee, String wechatNo,
            String authFlag) {
        this.agentCustId = agentCustId;
        this.agentFlag = agentFlag;
        this.agentGroupNo = agentGroupNo;
        this.agentType = agentType;
        this.bindMobile = bindMobile;
        this.createTime = createTime;
        this.followTime = followTime;
        this.loginAcct = loginAcct;
        this.loginPwd = loginPwd;
        this.nickname = nickname;
        this.openid = openid;
        this.qrCode = qrCode;
        this.state = state;
        this.tenantNo = tenantNo;
        this.updateTime = updateTime;
        this.chnlType = chnlType;
        this.headImgUrl = headImgUrl;
        this.cardNo = cardNo;
        this.custLevel = custLevel;
        this.custName = custName;
        this.headimgurl = headimgurl;
        this.lastLoginTime = lastLoginTime;
        this.totalFee = totalFee;
        this.wechatNo = wechatNo;
        this.authFlag = authFlag;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "cust_id", unique = true, nullable = false)
    public Long getCustId() {
        return this.custId;
    }

    public void setCustId(Long custId) {
        this.custId = custId;
    }

    @Column(name = "agent_cust_id")
    public Long getAgentCustId() {
        return this.agentCustId;
    }

    public void setAgentCustId(Long agentCustId) {
        this.agentCustId = agentCustId;
    }

    @Column(name = "agent_flag", nullable = false, length = 4)
    public String getAgentFlag() {
        return this.agentFlag;
    }

    public void setAgentFlag(String agentFlag) {
        this.agentFlag = agentFlag;
    }

    @Column(name = "agent_group_no", length = 16)
    public String getAgentGroupNo() {
        return this.agentGroupNo;
    }

    public void setAgentGroupNo(String agentGroupNo) {
        this.agentGroupNo = agentGroupNo;
    }

    @Column(name = "agent_type", length = 4)
    public String getAgentType() {
        return this.agentType;
    }

    public void setAgentType(String agentType) {
        this.agentType = agentType;
    }

    @Column(name = "bind_mobile", length = 11)
    public String getBindMobile() {
        return this.bindMobile;
    }

    public void setBindMobile(String bindMobile) {
        this.bindMobile = bindMobile;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "create_time", nullable = false, length = 19)
    public Date getCreateTime() {
        return this.createTime;
    }

    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "follow_time", length = 19)
    public Date getFollowTime() {
        return this.followTime;
    }

    public void setFollowTime(Date followTime) {
        this.followTime = followTime;
    }

    @Column(name = "login_acct", length = 32)
    public String getLoginAcct() {
        return this.loginAcct;
    }

    public void setLoginAcct(String loginAcct) {
        this.loginAcct = loginAcct;
    }

    @Column(name = "login_pwd", length = 128)
    public String getLoginPwd() {
        return this.loginPwd;
    }

    public void setLoginPwd(String loginPwd) {
        this.loginPwd = loginPwd;
    }

    @Column(name = "nickname", length = 64)
    public String getNickname() {
        return this.nickname;
    }

    public void setNickname(String nickname) {
        this.nickname = nickname;
    }

    @Column(name = "openid", length = 64)
    public String getOpenid() {
        return this.openid;
    }

    public void setOpenid(String openid) {
        this.openid = openid;
    }

    @Column(name = "qr_code", length = 128)
    public String getQrCode() {
        return this.qrCode;
    }

    public void setQrCode(String qrCode) {
        this.qrCode = qrCode;
    }

    @Column(name = "state", nullable = false, length = 4)
    public String getState() {
        return this.state;
    }

    public void setState(String state) {
        this.state = state;
    }

    @Column(name = "tenant_no", nullable = false, length = 32)
    public String getTenantNo() {
        return this.tenantNo;
    }

    public void setTenantNo(String tenantNo) {
        this.tenantNo = tenantNo;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "update_time", length = 19)
    public Date getUpdateTime() {
        return this.updateTime;
    }

    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    @Column(name = "chnl_type")
    public Integer getChnlType() {
        return this.chnlType;
    }

    public void setChnlType(Integer chnlType) {
        this.chnlType = chnlType;
    }

    @Column(name = "head_img_url", length = 128)
    public String getHeadImgUrl() {
        return this.headImgUrl;
    }

    public void setHeadImgUrl(String headImgUrl) {
        this.headImgUrl = headImgUrl;
    }

    @Column(name = "card_no", length = 32)
    public String getCardNo() {
        return this.cardNo;
    }

    public void setCardNo(String cardNo) {
        this.cardNo = cardNo;
    }

    @Column(name = "cust_level", length = 4)
    public String getCustLevel() {
        return this.custLevel;
    }

    public void setCustLevel(String custLevel) {
        this.custLevel = custLevel;
    }

    @Column(name = "cust_name", length = 64)
    public String getCustName() {
        return this.custName;
    }

    public void setCustName(String custName) {
        this.custName = custName;
    }

    @Column(name = "headimgurl", length = 128)
    public String getHeadimgurl() {
        return this.headimgurl;
    }

    public void setHeadimgurl(String headimgurl) {
        this.headimgurl = headimgurl;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "last_login_time", length = 19)
    public Date getLastLoginTime() {
        return this.lastLoginTime;
    }

    public void setLastLoginTime(Date lastLoginTime) {
        this.lastLoginTime = lastLoginTime;
    }

    @Column(name = "total_fee", precision = 10, scale = 0)
    public Long getTotalFee() {
        return this.totalFee;
    }

    public void setTotalFee(Long totalFee) {
        this.totalFee = totalFee;
    }

    @Column(name = "wechat_no", length = 64)
    public String getWechatNo() {
        return this.wechatNo;
    }

    public void setWechatNo(String wechatNo) {
        this.wechatNo = wechatNo;
    }

    @Column(name = "auth_flag", nullable = false, length = 4)
    public String getAuthFlag() {
        return this.authFlag;
    }

    public void setAuthFlag(String authFlag) {
        this.authFlag = authFlag;
    }

}
