package com.eroom.web.entity.po;
// Generated 2017-5-24 16:38:21 by Hibernate Tools 5.2.1.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * CmCust generated by hbm2java
 */
@Entity
@Table(name = "cm_cust", catalog = "eroom")
public class CmCust implements java.io.Serializable {

    private Long custId;

    private String address;

    private String assetLevel;

    private String assignSaleFlag;

    private Date assignSaleTime;

    private String assignServiceFlag;

    private Date assignServiceTime;

    private String cityCode;

    private String contactQq;

    private String contactTel;

    private String contactTel2;

    private String contactTel3;

    private String contactWechat;

    private String createStaffNo;

    private Date createTime;

    private String custName;

    private String email;

    private String fromType;

    private Integer investAge;

    private String provinceCode;

    private String remark;

    private String saleDeptNo;

    private String saleStaffNo;

    private String serviceDeptNo;

    private String serviceStaffNo;

    private String sex;

    private String state;

    private String tenantNo;

    private String updateStaffNo;

    private Date updateTime;

    private String wxNickname;

    private String wxOpenid;

    private Date assignSaleStaffTime;

    public CmCust() {
    }

    public CmCust(Date createTime, String custName, String state, String tenantNo) {
        this.createTime = createTime;
        this.custName = custName;
        this.state = state;
        this.tenantNo = tenantNo;
    }

    public CmCust(String address, String assetLevel, String assignSaleFlag, Date assignSaleTime,
            String assignServiceFlag, Date assignServiceTime, String cityCode, String contactQq,
            String contactTel, String contactTel2, String contactTel3, String contactWechat,
            String createStaffNo, Date createTime, String custName, String email, String fromType,
            Integer investAge, String provinceCode, String remark, String saleDeptNo,
            String saleStaffNo, String serviceDeptNo, String serviceStaffNo, String sex,
            String state, String tenantNo, String updateStaffNo, Date updateTime, String wxNickname,
            String wxOpenid, Date assignSaleStaffTime) {
        this.address = address;
        this.assetLevel = assetLevel;
        this.assignSaleFlag = assignSaleFlag;
        this.assignSaleTime = assignSaleTime;
        this.assignServiceFlag = assignServiceFlag;
        this.assignServiceTime = assignServiceTime;
        this.cityCode = cityCode;
        this.contactQq = contactQq;
        this.contactTel = contactTel;
        this.contactTel2 = contactTel2;
        this.contactTel3 = contactTel3;
        this.contactWechat = contactWechat;
        this.createStaffNo = createStaffNo;
        this.createTime = createTime;
        this.custName = custName;
        this.email = email;
        this.fromType = fromType;
        this.investAge = investAge;
        this.provinceCode = provinceCode;
        this.remark = remark;
        this.saleDeptNo = saleDeptNo;
        this.saleStaffNo = saleStaffNo;
        this.serviceDeptNo = serviceDeptNo;
        this.serviceStaffNo = serviceStaffNo;
        this.sex = sex;
        this.state = state;
        this.tenantNo = tenantNo;
        this.updateStaffNo = updateStaffNo;
        this.updateTime = updateTime;
        this.wxNickname = wxNickname;
        this.wxOpenid = wxOpenid;
        this.assignSaleStaffTime = assignSaleStaffTime;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "cust_id", unique = true, nullable = false)
    public Long getCustId() {
        return this.custId;
    }

    public void setCustId(Long custId) {
        this.custId = custId;
    }

    @Column(name = "address", length = 256)
    public String getAddress() {
        return this.address;
    }

    public void setAddress(String address) {
        this.address = address;
    }

    @Column(name = "asset_level", length = 10)
    public String getAssetLevel() {
        return this.assetLevel;
    }

    public void setAssetLevel(String assetLevel) {
        this.assetLevel = assetLevel;
    }

    @Column(name = "assign_sale_flag", length = 4)
    public String getAssignSaleFlag() {
        return this.assignSaleFlag;
    }

    public void setAssignSaleFlag(String assignSaleFlag) {
        this.assignSaleFlag = assignSaleFlag;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "assign_sale_time", length = 19)
    public Date getAssignSaleTime() {
        return this.assignSaleTime;
    }

    public void setAssignSaleTime(Date assignSaleTime) {
        this.assignSaleTime = assignSaleTime;
    }

    @Column(name = "assign_service_flag", length = 4)
    public String getAssignServiceFlag() {
        return this.assignServiceFlag;
    }

    public void setAssignServiceFlag(String assignServiceFlag) {
        this.assignServiceFlag = assignServiceFlag;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "assign_service_time", length = 19)
    public Date getAssignServiceTime() {
        return this.assignServiceTime;
    }

    public void setAssignServiceTime(Date assignServiceTime) {
        this.assignServiceTime = assignServiceTime;
    }

    @Column(name = "city_code", length = 16)
    public String getCityCode() {
        return this.cityCode;
    }

    public void setCityCode(String cityCode) {
        this.cityCode = cityCode;
    }

    @Column(name = "contact_qq", length = 16)
    public String getContactQq() {
        return this.contactQq;
    }

    public void setContactQq(String contactQq) {
        this.contactQq = contactQq;
    }

    @Column(name = "contact_tel", length = 12)
    public String getContactTel() {
        return this.contactTel;
    }

    public void setContactTel(String contactTel) {
        this.contactTel = contactTel;
    }

    @Column(name = "contact_tel2", length = 12)
    public String getContactTel2() {
        return this.contactTel2;
    }

    public void setContactTel2(String contactTel2) {
        this.contactTel2 = contactTel2;
    }

    @Column(name = "contact_tel3", length = 16)
    public String getContactTel3() {
        return this.contactTel3;
    }

    public void setContactTel3(String contactTel3) {
        this.contactTel3 = contactTel3;
    }

    @Column(name = "contact_wechat", length = 32)
    public String getContactWechat() {
        return this.contactWechat;
    }

    public void setContactWechat(String contactWechat) {
        this.contactWechat = contactWechat;
    }

    @Column(name = "create_staff_no", length = 16)
    public String getCreateStaffNo() {
        return this.createStaffNo;
    }

    public void setCreateStaffNo(String createStaffNo) {
        this.createStaffNo = createStaffNo;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "create_time", nullable = false, length = 19)
    public Date getCreateTime() {
        return this.createTime;
    }

    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    @Column(name = "cust_name", nullable = false, length = 32)
    public String getCustName() {
        return this.custName;
    }

    public void setCustName(String custName) {
        this.custName = custName;
    }

    @Column(name = "email", length = 64)
    public String getEmail() {
        return this.email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    @Column(name = "fromType", length = 8)
    public String getFromType() {
        return this.fromType;
    }

    public void setFromType(String fromType) {
        this.fromType = fromType;
    }

    @Column(name = "invest_age")
    public Integer getInvestAge() {
        return this.investAge;
    }

    public void setInvestAge(Integer investAge) {
        this.investAge = investAge;
    }

    @Column(name = "province_code", length = 16)
    public String getProvinceCode() {
        return this.provinceCode;
    }

    public void setProvinceCode(String provinceCode) {
        this.provinceCode = provinceCode;
    }

    @Column(name = "remark", length = 516)
    public String getRemark() {
        return this.remark;
    }

    public void setRemark(String remark) {
        this.remark = remark;
    }

    @Column(name = "sale_dept_no", length = 16)
    public String getSaleDeptNo() {
        return this.saleDeptNo;
    }

    public void setSaleDeptNo(String saleDeptNo) {
        this.saleDeptNo = saleDeptNo;
    }

    @Column(name = "sale_staff_no", length = 16)
    public String getSaleStaffNo() {
        return this.saleStaffNo;
    }

    public void setSaleStaffNo(String saleStaffNo) {
        this.saleStaffNo = saleStaffNo;
    }

    @Column(name = "service_dept_no", length = 16)
    public String getServiceDeptNo() {
        return this.serviceDeptNo;
    }

    public void setServiceDeptNo(String serviceDeptNo) {
        this.serviceDeptNo = serviceDeptNo;
    }

    @Column(name = "service_staff_no", length = 16)
    public String getServiceStaffNo() {
        return this.serviceStaffNo;
    }

    public void setServiceStaffNo(String serviceStaffNo) {
        this.serviceStaffNo = serviceStaffNo;
    }

    @Column(name = "sex", length = 4)
    public String getSex() {
        return this.sex;
    }

    public void setSex(String sex) {
        this.sex = sex;
    }

    @Column(name = "state", nullable = false, length = 4)
    public String getState() {
        return this.state;
    }

    public void setState(String state) {
        this.state = state;
    }

    @Column(name = "tenant_no", nullable = false, length = 32)
    public String getTenantNo() {
        return this.tenantNo;
    }

    public void setTenantNo(String tenantNo) {
        this.tenantNo = tenantNo;
    }

    @Column(name = "update_staff_no", length = 16)
    public String getUpdateStaffNo() {
        return this.updateStaffNo;
    }

    public void setUpdateStaffNo(String updateStaffNo) {
        this.updateStaffNo = updateStaffNo;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "update_time", length = 19)
    public Date getUpdateTime() {
        return this.updateTime;
    }

    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    @Column(name = "wx_nickname", length = 32)
    public String getWxNickname() {
        return this.wxNickname;
    }

    public void setWxNickname(String wxNickname) {
        this.wxNickname = wxNickname;
    }

    @Column(name = "wx_openid", length = 64)
    public String getWxOpenid() {
        return this.wxOpenid;
    }

    public void setWxOpenid(String wxOpenid) {
        this.wxOpenid = wxOpenid;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "assign_sale_staff_time", length = 19)
    public Date getAssignSaleStaffTime() {
        return this.assignSaleStaffTime;
    }

    public void setAssignSaleStaffTime(Date assignSaleStaffTime) {
        this.assignSaleStaffTime = assignSaleStaffTime;
    }

}
