package com.eroom.web.entity.po;
// Generated 2017-5-24 16:38:21 by Hibernate Tools 5.2.1.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * CmImportLog generated by hbm2java
 */
@Entity
@Table(name = "cm_import_log", catalog = "eroom")
public class CmImportLog implements java.io.Serializable {

    private Long logId;

    private String createStaffNo;

    private Date createTime;

    private String importFileName;

    private String importFileUrl;

    private String resultFileName;

    private String resultFileUrl;

    private String state;

    private String stateDesc;

    private String tenantNo;

    private String updateStaffNo;

    private Date updateTime;

    public CmImportLog() {
    }

    public CmImportLog(Date createTime, String importFileName, String importFileUrl, String state,
            String tenantNo) {
        this.createTime = createTime;
        this.importFileName = importFileName;
        this.importFileUrl = importFileUrl;
        this.state = state;
        this.tenantNo = tenantNo;
    }

    public CmImportLog(String createStaffNo, Date createTime, String importFileName,
            String importFileUrl, String resultFileName, String resultFileUrl, String state,
            String stateDesc, String tenantNo, String updateStaffNo, Date updateTime) {
        this.createStaffNo = createStaffNo;
        this.createTime = createTime;
        this.importFileName = importFileName;
        this.importFileUrl = importFileUrl;
        this.resultFileName = resultFileName;
        this.resultFileUrl = resultFileUrl;
        this.state = state;
        this.stateDesc = stateDesc;
        this.tenantNo = tenantNo;
        this.updateStaffNo = updateStaffNo;
        this.updateTime = updateTime;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "log_id", unique = true, nullable = false)
    public Long getLogId() {
        return this.logId;
    }

    public void setLogId(Long logId) {
        this.logId = logId;
    }

    @Column(name = "create_staff_no", length = 16)
    public String getCreateStaffNo() {
        return this.createStaffNo;
    }

    public void setCreateStaffNo(String createStaffNo) {
        this.createStaffNo = createStaffNo;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "create_time", nullable = false, length = 19)
    public Date getCreateTime() {
        return this.createTime;
    }

    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    @Column(name = "import_file_name", nullable = false, length = 32)
    public String getImportFileName() {
        return this.importFileName;
    }

    public void setImportFileName(String importFileName) {
        this.importFileName = importFileName;
    }

    @Column(name = "import_file_url", nullable = false, length = 128)
    public String getImportFileUrl() {
        return this.importFileUrl;
    }

    public void setImportFileUrl(String importFileUrl) {
        this.importFileUrl = importFileUrl;
    }

    @Column(name = "result_file_name", length = 32)
    public String getResultFileName() {
        return this.resultFileName;
    }

    public void setResultFileName(String resultFileName) {
        this.resultFileName = resultFileName;
    }

    @Column(name = "result_file_url", length = 128)
    public String getResultFileUrl() {
        return this.resultFileUrl;
    }

    public void setResultFileUrl(String resultFileUrl) {
        this.resultFileUrl = resultFileUrl;
    }

    @Column(name = "state", nullable = false, length = 4)
    public String getState() {
        return this.state;
    }

    public void setState(String state) {
        this.state = state;
    }

    @Column(name = "state_desc", length = 512)
    public String getStateDesc() {
        return this.stateDesc;
    }

    public void setStateDesc(String stateDesc) {
        this.stateDesc = stateDesc;
    }

    @Column(name = "tenant_no", nullable = false, length = 32)
    public String getTenantNo() {
        return this.tenantNo;
    }

    public void setTenantNo(String tenantNo) {
        this.tenantNo = tenantNo;
    }

    @Column(name = "update_staff_no", length = 16)
    public String getUpdateStaffNo() {
        return this.updateStaffNo;
    }

    public void setUpdateStaffNo(String updateStaffNo) {
        this.updateStaffNo = updateStaffNo;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "update_time", length = 19)
    public Date getUpdateTime() {
        return this.updateTime;
    }

    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

}
