package com.eroom.web.entity.po;
// Generated 2017-5-24 16:38:21 by Hibernate Tools 5.2.1.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * CustInfo generated by hbm2java
 */
@Entity
@Table(name = "cust_info", catalog = "eroom")
public class CustInfo implements java.io.Serializable {

    private Long custId;

    private String name;

    private String phone;

    private String qq;

    private String wechat;

    private String nickName;

    private String openid;

    private String email;

    private String sex;

    private String remark;

    private String state;

    private Date createTime;

    private Date updateTime;

    private String authPhone;

    private String isOwner;

    private String account;

    private String password;

    private String image;

    public CustInfo() {
    }

    public CustInfo(String openid, String state, Date createTime, String authPhone,
                    String isOwner) {
        this.openid = openid;
        this.state = state;
        this.createTime = createTime;
        this.authPhone = authPhone;
        this.isOwner = isOwner;
    }

    public CustInfo(String name, String phone, String qq, String wechat, String nickName,
                    String openid, String email, String sex, String remark, String state, Date createTime,
                    Date updateTime, String authPhone, String isOwner, String account, String password,
                    String image) {
        this.name = name;
        this.phone = phone;
        this.qq = qq;
        this.wechat = wechat;
        this.nickName = nickName;
        this.openid = openid;
        this.email = email;
        this.sex = sex;
        this.remark = remark;
        this.state = state;
        this.createTime = createTime;
        this.updateTime = updateTime;
        this.authPhone = authPhone;
        this.isOwner = isOwner;
        this.account = account;
        this.password = password;
        this.image = image;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "cust_id", unique = true, nullable = false)
    public Long getCustId() {
        return this.custId;
    }

    public void setCustId(Long custId) {
        this.custId = custId;
    }

    @Column(name = "name", length = 8)
    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    @Column(name = "phone", length = 16)
    public String getPhone() {
        return this.phone;
    }

    public void setPhone(String phone) {
        this.phone = phone;
    }

    @Column(name = "qq", length = 16)
    public String getQq() {
        return this.qq;
    }

    public void setQq(String qq) {
        this.qq = qq;
    }

    @Column(name = "wechat", length = 16)
    public String getWechat() {
        return this.wechat;
    }

    public void setWechat(String wechat) {
        this.wechat = wechat;
    }

    @Column(name = "nick_name", length = 16)
    public String getNickName() {
        return this.nickName;
    }

    public void setNickName(String nickName) {
        this.nickName = nickName;
    }

    @Column(name = "openid", nullable = false, length = 32)
    public String getOpenid() {
        return this.openid;
    }

    public void setOpenid(String openid) {
        this.openid = openid;
    }

    @Column(name = "email", length = 16)
    public String getEmail() {
        return this.email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    @Column(name = "sex", length = 8)
    public String getSex() {
        return this.sex;
    }

    public void setSex(String sex) {
        this.sex = sex;
    }

    @Column(name = "remark", length = 64)
    public String getRemark() {
        return this.remark;
    }

    public void setRemark(String remark) {
        this.remark = remark;
    }

    @Column(name = "state", nullable = false, length = 4)
    public String getState() {
        return this.state;
    }

    public void setState(String state) {
        this.state = state;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "create_time", nullable = false, length = 19)
    public Date getCreateTime() {
        return this.createTime;
    }

    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "update_time", length = 19)
    public Date getUpdateTime() {
        return this.updateTime;
    }

    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    @Column(name = "auth_phone", length = 4)
    public String getAuthPhone() {
        return this.authPhone;
    }

    public void setAuthPhone(String authPhone) {
        this.authPhone = authPhone;
    }

    @Column(name = "is_owner", nullable = false, length = 4)
    public String getIsOwner() {
        return this.isOwner;
    }

    public void setIsOwner(String isOwner) {
        this.isOwner = isOwner;
    }

    @Column(name = "account", length = 16)
    public String getAccount() {
        return this.account;
    }

    public void setAccount(String account) {
        this.account = account;
    }

    @Column(name = "password", length = 16)
    public String getPassword() {
        return this.password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    @Column(name = "image", length = 64)
    public String getImage() {
        return this.image;
    }

    public void setImage(String image) {
        this.image = image;
    }

    @Override
    public String toString() {
        return "CustInfo{" +
                "custId=" + custId +
                ", name='" + name + '\'' +
                ", phone='" + phone + '\'' +
                ", qq='" + qq + '\'' +
                ", wechat='" + wechat + '\'' +
                ", nickName='" + nickName + '\'' +
                ", openid='" + openid + '\'' +
                ", email='" + email + '\'' +
                ", sex='" + sex + '\'' +
                ", remark='" + remark + '\'' +
                ", state='" + state + '\'' +
                ", createTime=" + createTime +
                ", updateTime=" + updateTime +
                ", authPhone='" + authPhone + '\'' +
                ", isOwner='" + isOwner + '\'' +
                ", account='" + account + '\'' +
                ", password='" + password + '\'' +
                ", image='" + image + '\'' +
                '}';
    }
}
