package com.eroom.web.entity.po;

import javax.persistence.*;
import java.math.BigDecimal;
import java.util.Date;

import static javax.persistence.GenerationType.IDENTITY;

/**
 * RoomRent generated by hbm2java
 */
@Entity
@Table(name = "room_rent", catalog = "eroom")
public class RoomRent implements java.io.Serializable {

    private Long rentId;

    private long roomId;

    private long custOwnerId;

    private String rentType;

    private BigDecimal price;

    private String payType;

    private long bedroomId;

    private Long custRenterId;

    private Date startTime;

    private Date endTime;

    private Date createTime;

    private Date updateTime;

    private int sortId;

    private String rentState;

    public RoomRent() {
    }

    public RoomRent(long roomId, long custOwnerId, BigDecimal price, String payType,
                    long bedroomId, Date createTime, int sortId) {
        this.roomId = roomId;
        this.custOwnerId = custOwnerId;
        this.price = price;
        this.payType = payType;
        this.bedroomId = bedroomId;
        this.createTime = createTime;
        this.sortId = sortId;
    }

    public RoomRent(long roomId, long custOwnerId, String rentType, BigDecimal price,
                    String payType, long bedroomId, Long custRenterId, Date startTime,
                    Date endTime, Date createTime, Date updateTime, int sortId, String rentState) {
        this.roomId = roomId;
        this.custOwnerId = custOwnerId;
        this.rentType = rentType;
        this.price = price;
        this.payType = payType;
        this.bedroomId = bedroomId;
        this.custRenterId = custRenterId;
        this.startTime = startTime;
        this.endTime = endTime;
        this.createTime = createTime;
        this.updateTime = updateTime;
        this.sortId = sortId;
        this.rentState = rentState;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "rent_id", unique = true, nullable = false)
    public Long getRentId() {
        return this.rentId;
    }

    public void setRentId(Long rentId) {
        this.rentId = rentId;
    }

    @Column(name = "room_id", nullable = false)
    public long getRoomId() {
        return this.roomId;
    }

    public void setRoomId(long roomId) {
        this.roomId = roomId;
    }

    @Column(name = "cust_owner_id", nullable = false)
    public long getCustOwnerId() {
        return this.custOwnerId;
    }

    public void setCustOwnerId(long custOwnerId) {
        this.custOwnerId = custOwnerId;
    }

    @Column(name = "rent_type", length = 4)
    public String getRentType() {
        return this.rentType;
    }

    public void setRentType(String rentType) {
        this.rentType = rentType;
    }

    @Column(name = "price", nullable = false, precision = 10)
    public BigDecimal getPrice() {
        return this.price;
    }

    public void setPrice(BigDecimal price) {
        this.price = price;
    }

    @Column(name = "pay_type", nullable = false, length = 8)
    public String getPayType() {
        return this.payType;
    }

    public void setPayType(String payType) {
        this.payType = payType;
    }

    @Column(name = "bedroom_id", nullable = false)
    public long getBedroomId() {
        return this.bedroomId;
    }

    public void setBedroomId(long bedroomId) {
        this.bedroomId = bedroomId;
    }

    @Column(name = "cust_renter_id")
    public Long getCustRenterId() {
        return this.custRenterId;
    }

    public void setCustRenterId(Long custRenterId) {
        this.custRenterId = custRenterId;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "start_time", length = 19)
    public Date getStartTime() {
        return this.startTime;
    }

    public void setStartTime(Date startTime) {
        this.startTime = startTime;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "end_time", length = 19)
    public Date getEndTime() {
        return this.endTime;
    }

    public void setEndTime(Date endTime) {
        this.endTime = endTime;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "create_time", nullable = false, length = 19)
    public Date getCreateTime() {
        return this.createTime;
    }

    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "update_time", length = 19)
    public Date getUpdateTime() {
        return this.updateTime;
    }

    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    @Column(name = "sort_id", nullable = false)
    public int getSortId() {
        return this.sortId;
    }

    public void setSortId(int sortId) {
        this.sortId = sortId;
    }

    @Column(name = "rent_state", length = 4)
    public String getRentState() {
        return this.rentState;
    }

    public void setRentState(String rentState) {
        this.rentState = rentState;
    }

}
