package com.eroom.web.entity.po;
// Generated 2017-5-24 16:38:21 by Hibernate Tools 5.2.1.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * RoomTask generated by hbm2java
 */
@Entity
@Table(name = "t_room_task", catalog = "eroom")
public class RoomTask implements java.io.Serializable {

    private Long taskId;

    private long roomId;

    private long executeCustId;

    private long custId;

    private String content;

    private String taskList;

    private Date createTime;

    private Date updateTime;

    private Date startTime;

    private Date endTime;

    private String remark;

    private String type;

    private String taskState;

    public RoomTask() {
    }

    public RoomTask(long roomId, long executeCustId, long custId, Date createTime, String state) {
        this.roomId = roomId;
        this.executeCustId = executeCustId;
        this.custId = custId;
        this.createTime = createTime;
    }

    public RoomTask(long roomId, long executeCustId, long custId, String content, String taskList,
                    Date createTime, Date updateTime, String state, Date startTime, Date endTime,
                    String remark, String type, String taskState) {
        this.roomId = roomId;
        this.executeCustId = executeCustId;
        this.custId = custId;
        this.content = content;
        this.taskList = taskList;
        this.createTime = createTime;
        this.updateTime = updateTime;
        this.startTime = startTime;
        this.endTime = endTime;
        this.remark = remark;
        this.type = type;
        this.taskState = taskState;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)

    @Column(name = "task_id", unique = true, nullable = false)
    public Long getTaskId() {
        return this.taskId;
    }

    public void setTaskId(Long taskId) {
        this.taskId = taskId;
    }

    @Column(name = "room_id", nullable = false)
    public long getRoomId() {
        return this.roomId;
    }

    public void setRoomId(long roomId) {
        this.roomId = roomId;
    }

    @Column(name = "execute_cust_id", nullable = false)
    public long getExecuteCustId() {
        return this.executeCustId;
    }

    public void setExecuteCustId(long executeCustId) {
        this.executeCustId = executeCustId;
    }

    @Column(name = "cust_id", nullable = false)
    public long getCustId() {
        return this.custId;
    }

    public void setCustId(long custId) {
        this.custId = custId;
    }

    @Column(name = "content", length = 225)
    public String getContent() {
        return this.content;
    }

    public void setContent(String content) {
        this.content = content;
    }

    @Column(name = "task_list", length = 64)
    public String getTaskList() {
        return this.taskList;
    }

    public void setTaskList(String taskList) {
        this.taskList = taskList;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "create_time", nullable = false, length = 19)
    public Date getCreateTime() {
        return this.createTime;
    }

    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "update_time", length = 19)
    public Date getUpdateTime() {
        return this.updateTime;
    }

    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "start_time", length = 19)
    public Date getStartTime() {
        return this.startTime;
    }

    public void setStartTime(Date startTime) {
        this.startTime = startTime;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "end_time", length = 19)
    public Date getEndTime() {
        return this.endTime;
    }

    public void setEndTime(Date endTime) {
        this.endTime = endTime;
    }

    @Column(name = "remark", length = 225)
    public String getRemark() {
        return this.remark;
    }

    public void setRemark(String remark) {
        this.remark = remark;
    }

    @Column(name = "type", length = 8)
    public String getType() {
        return this.type;
    }

    public void setType(String type) {
        this.type = type;
    }

    @Column(name = "task_state", length = 4)
    public String getTaskState() {
        return this.taskState;
    }

    public void setTaskState(String taskState) {
        this.taskState = taskState;
    }

}
