package com.eroom.web.entity.po;
// Generated 2017-5-24 16:38:21 by Hibernate Tools 5.2.1.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * SystemBaseExt generated by hbm2java
 */
@Entity
@Table(name = "system_base_ext", catalog = "eroom")
public class SystemBaseExt implements java.io.Serializable {

    private long systemId;

    private String qrCodeImageUrl;

    private String shareLogoUrl;

    private String agentLogoUrl;

    private String shareIconUrl;

    private String shareTitle;

    private String shareDesc;

    private String contactUs;

    private String aboutUrl;

    private String serviceUrl;

    private String welcomeWord;

    private String createStaffNo;

    private Date createTime;

    private String updateStaffNo;

    private Date updateTime;

    public SystemBaseExt() {
    }

    public SystemBaseExt(long systemId) {
        this.systemId = systemId;
    }

    public SystemBaseExt(long systemId, String qrCodeImageUrl, String shareLogoUrl,
            String agentLogoUrl, String shareIconUrl, String shareTitle, String shareDesc,
            String contactUs, String aboutUrl, String serviceUrl, String welcomeWord,
            String createStaffNo, Date createTime, String updateStaffNo, Date updateTime) {
        this.systemId = systemId;
        this.qrCodeImageUrl = qrCodeImageUrl;
        this.shareLogoUrl = shareLogoUrl;
        this.agentLogoUrl = agentLogoUrl;
        this.shareIconUrl = shareIconUrl;
        this.shareTitle = shareTitle;
        this.shareDesc = shareDesc;
        this.contactUs = contactUs;
        this.aboutUrl = aboutUrl;
        this.serviceUrl = serviceUrl;
        this.welcomeWord = welcomeWord;
        this.createStaffNo = createStaffNo;
        this.createTime = createTime;
        this.updateStaffNo = updateStaffNo;
        this.updateTime = updateTime;
    }

    @Id

    @Column(name = "system_id", unique = true, nullable = false)
    public long getSystemId() {
        return this.systemId;
    }

    public void setSystemId(long systemId) {
        this.systemId = systemId;
    }

    @Column(name = "qr_code_image_url", length = 128)
    public String getQrCodeImageUrl() {
        return this.qrCodeImageUrl;
    }

    public void setQrCodeImageUrl(String qrCodeImageUrl) {
        this.qrCodeImageUrl = qrCodeImageUrl;
    }

    @Column(name = "share_logo_url", length = 128)
    public String getShareLogoUrl() {
        return this.shareLogoUrl;
    }

    public void setShareLogoUrl(String shareLogoUrl) {
        this.shareLogoUrl = shareLogoUrl;
    }

    @Column(name = "agent_logo_url", length = 128)
    public String getAgentLogoUrl() {
        return this.agentLogoUrl;
    }

    public void setAgentLogoUrl(String agentLogoUrl) {
        this.agentLogoUrl = agentLogoUrl;
    }

    @Column(name = "share_icon_url", length = 128)
    public String getShareIconUrl() {
        return this.shareIconUrl;
    }

    public void setShareIconUrl(String shareIconUrl) {
        this.shareIconUrl = shareIconUrl;
    }

    @Column(name = "share_title", length = 64)
    public String getShareTitle() {
        return this.shareTitle;
    }

    public void setShareTitle(String shareTitle) {
        this.shareTitle = shareTitle;
    }

    @Column(name = "share_desc", length = 64)
    public String getShareDesc() {
        return this.shareDesc;
    }

    public void setShareDesc(String shareDesc) {
        this.shareDesc = shareDesc;
    }

    @Column(name = "contact_us", length = 256)
    public String getContactUs() {
        return this.contactUs;
    }

    public void setContactUs(String contactUs) {
        this.contactUs = contactUs;
    }

    @Column(name = "about_url", length = 128)
    public String getAboutUrl() {
        return this.aboutUrl;
    }

    public void setAboutUrl(String aboutUrl) {
        this.aboutUrl = aboutUrl;
    }

    @Column(name = "service_url", length = 128)
    public String getServiceUrl() {
        return this.serviceUrl;
    }

    public void setServiceUrl(String serviceUrl) {
        this.serviceUrl = serviceUrl;
    }

    @Column(name = "welcome_word", length = 256)
    public String getWelcomeWord() {
        return this.welcomeWord;
    }

    public void setWelcomeWord(String welcomeWord) {
        this.welcomeWord = welcomeWord;
    }

    @Column(name = "create_staff_no", length = 16)
    public String getCreateStaffNo() {
        return this.createStaffNo;
    }

    public void setCreateStaffNo(String createStaffNo) {
        this.createStaffNo = createStaffNo;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "create_time", length = 19)
    public Date getCreateTime() {
        return this.createTime;
    }

    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    @Column(name = "update_staff_no", length = 16)
    public String getUpdateStaffNo() {
        return this.updateStaffNo;
    }

    public void setUpdateStaffNo(String updateStaffNo) {
        this.updateStaffNo = updateStaffNo;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "update_time", length = 19)
    public Date getUpdateTime() {
        return this.updateTime;
    }

    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

}
