package com.eroom.web.entity.po;
// Generated 2017-5-24 16:38:21 by Hibernate Tools 5.2.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * SystemCfg generated by hbm2java
 */
@Entity
@Table(name = "system_cfg", catalog = "eroom")
public class SystemCfg implements java.io.Serializable {

    private Long cfgId;

    private String cfgCode;

    private String cfgDesc;

    private String cfgType;

    private String cfgValue;

    private String remark;

    public SystemCfg() {
    }

    public SystemCfg(String cfgCode, String cfgType, String cfgValue) {
        this.cfgCode = cfgCode;
        this.cfgType = cfgType;
        this.cfgValue = cfgValue;
    }

    public SystemCfg(String cfgCode, String cfgDesc, String cfgType, String cfgValue,
            String remark) {
        this.cfgCode = cfgCode;
        this.cfgDesc = cfgDesc;
        this.cfgType = cfgType;
        this.cfgValue = cfgValue;
        this.remark = remark;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)

    @Column(name = "cfg_id", unique = true, nullable = false)
    public Long getCfgId() {
        return this.cfgId;
    }

    public void setCfgId(Long cfgId) {
        this.cfgId = cfgId;
    }

    @Column(name = "cfg_code", nullable = false, length = 32)
    public String getCfgCode() {
        return this.cfgCode;
    }

    public void setCfgCode(String cfgCode) {
        this.cfgCode = cfgCode;
    }

    @Column(name = "cfg_desc", length = 128)
    public String getCfgDesc() {
        return this.cfgDesc;
    }

    public void setCfgDesc(String cfgDesc) {
        this.cfgDesc = cfgDesc;
    }

    @Column(name = "cfg_type", nullable = false, length = 32)
    public String getCfgType() {
        return this.cfgType;
    }

    public void setCfgType(String cfgType) {
        this.cfgType = cfgType;
    }

    @Column(name = "cfg_value", nullable = false, length = 128)
    public String getCfgValue() {
        return this.cfgValue;
    }

    public void setCfgValue(String cfgValue) {
        this.cfgValue = cfgValue;
    }

    @Column(name = "remark", length = 128)
    public String getRemark() {
        return this.remark;
    }

    public void setRemark(String remark) {
        this.remark = remark;
    }

}
