package com.eroom.web.entity.po;
// Generated 2017-5-24 16:38:21 by Hibernate Tools 5.2.1.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * SystemRole generated by hbm2java
 */
@Entity
@Table(name = "system_role", catalog = "eroom")
public class SystemRole implements java.io.Serializable {

    private Long roleId;

    private String createStaffNo;

    private Date createTime;

    private String dataAuth;

    private Date endTime;

    private String objectId;

    private String objectType;

    private String roleDesc;

    private String roleName;

    private Date startTime;

    private String state;

    private String updateStaffNo;

    private Date updateTime;

    public SystemRole() {
    }

    public SystemRole(Date createTime, String dataAuth, Date endTime, String objectType,
            String roleName, Date startTime, String state) {
        this.createTime = createTime;
        this.dataAuth = dataAuth;
        this.endTime = endTime;
        this.objectType = objectType;
        this.roleName = roleName;
        this.startTime = startTime;
        this.state = state;
    }

    public SystemRole(String createStaffNo, Date createTime, String dataAuth, Date endTime,
            String objectId, String objectType, String roleDesc, String roleName, Date startTime,
            String state, String updateStaffNo, Date updateTime) {
        this.createStaffNo = createStaffNo;
        this.createTime = createTime;
        this.dataAuth = dataAuth;
        this.endTime = endTime;
        this.objectId = objectId;
        this.objectType = objectType;
        this.roleDesc = roleDesc;
        this.roleName = roleName;
        this.startTime = startTime;
        this.state = state;
        this.updateStaffNo = updateStaffNo;
        this.updateTime = updateTime;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)

    @Column(name = "role_id", unique = true, nullable = false)
    public Long getRoleId() {
        return this.roleId;
    }

    public void setRoleId(Long roleId) {
        this.roleId = roleId;
    }

    @Column(name = "create_staff_no", length = 16)
    public String getCreateStaffNo() {
        return this.createStaffNo;
    }

    public void setCreateStaffNo(String createStaffNo) {
        this.createStaffNo = createStaffNo;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "create_time", nullable = false, length = 19)
    public Date getCreateTime() {
        return this.createTime;
    }

    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    @Column(name = "data_auth", nullable = false, length = 4)
    public String getDataAuth() {
        return this.dataAuth;
    }

    public void setDataAuth(String dataAuth) {
        this.dataAuth = dataAuth;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "end_time", nullable = false, length = 19)
    public Date getEndTime() {
        return this.endTime;
    }

    public void setEndTime(Date endTime) {
        this.endTime = endTime;
    }

    @Column(name = "object_id", length = 32)
    public String getObjectId() {
        return this.objectId;
    }

    public void setObjectId(String objectId) {
        this.objectId = objectId;
    }

    @Column(name = "object_type", nullable = false, length = 4)
    public String getObjectType() {
        return this.objectType;
    }

    public void setObjectType(String objectType) {
        this.objectType = objectType;
    }

    @Column(name = "role_desc", length = 128)
    public String getRoleDesc() {
        return this.roleDesc;
    }

    public void setRoleDesc(String roleDesc) {
        this.roleDesc = roleDesc;
    }

    @Column(name = "role_name", nullable = false, length = 32)
    public String getRoleName() {
        return this.roleName;
    }

    public void setRoleName(String roleName) {
        this.roleName = roleName;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "start_time", nullable = false, length = 19)
    public Date getStartTime() {
        return this.startTime;
    }

    public void setStartTime(Date startTime) {
        this.startTime = startTime;
    }

    @Column(name = "state", nullable = false, length = 4)
    public String getState() {
        return this.state;
    }

    public void setState(String state) {
        this.state = state;
    }

    @Column(name = "update_staff_no", length = 16)
    public String getUpdateStaffNo() {
        return this.updateStaffNo;
    }

    public void setUpdateStaffNo(String updateStaffNo) {
        this.updateStaffNo = updateStaffNo;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "update_time", length = 19)
    public Date getUpdateTime() {
        return this.updateTime;
    }

    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

}
