package com.eroom.web.entity.po;
// Generated 2017-5-24 16:38:21 by Hibernate Tools 5.2.1.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * SystemLoginLog generated by hbm2java
 */
@Entity
@Table(name = "system_login_log", catalog = "eroom")
public class SystemLoginLog implements java.io.Serializable {

    private Long logId;

    private String browser;

    private String ip;

    private Date loginDate;

    private long staffId;

    private String tenantNo;

    public SystemLoginLog() {
    }

    public SystemLoginLog(long staffId, String tenantNo) {
        this.staffId = staffId;
        this.tenantNo = tenantNo;
    }

    public SystemLoginLog(String browser, String ip, Date loginDate, long staffId,
            String tenantNo) {
        this.browser = browser;
        this.ip = ip;
        this.loginDate = loginDate;
        this.staffId = staffId;
        this.tenantNo = tenantNo;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)

    @Column(name = "log_id", unique = true, nullable = false)
    public Long getLogId() {
        return this.logId;
    }

    public void setLogId(Long logId) {
        this.logId = logId;
    }

    @Column(name = "browser", length = 32)
    public String getBrowser() {
        return this.browser;
    }

    public void setBrowser(String browser) {
        this.browser = browser;
    }

    @Column(name = "ip", length = 32)
    public String getIp() {
        return this.ip;
    }

    public void setIp(String ip) {
        this.ip = ip;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "login_date", length = 19)
    public Date getLoginDate() {
        return this.loginDate;
    }

    public void setLoginDate(Date loginDate) {
        this.loginDate = loginDate;
    }

    @Column(name = "staff_id", nullable = false)
    public long getStaffId() {
        return this.staffId;
    }

    public void setStaffId(long staffId) {
        this.staffId = staffId;
    }

    @Column(name = "tenant_no", nullable = false, length = 32)
    public String getTenantNo() {
        return this.tenantNo;
    }

    public void setTenantNo(String tenantNo) {
        this.tenantNo = tenantNo;
    }

}
