package com.eroom.web.entity.po;
// Generated 2017-5-24 16:38:21 by Hibernate Tools 5.2.1.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * SystemBase generated by hbm2java
 */
@Entity
@Table(name = "system_base", catalog = "eroom")
public class SystemBase implements java.io.Serializable {

    private Integer systemId;

    private String appVersion;

    private String appid;

    private String appscret;

    private String createStaffNo;

    private Date createTime;

    private Integer state;

    private String tenantName;

    private String updateStaffNo;

    private Date updateTime;

    private String wechatOrigId;

    private String accessToken;

    private String apiTicket;

    private Date accessTokenTime;

    private Date apiTicketTime;

    public SystemBase() {
    }

    public SystemBase(Date createTime) {
        this.createTime = createTime;
    }

    public SystemBase(String appVersion, String appid, String appscret, String createStaffNo,
            Date createTime, Integer state, String tenantName, String updateStaffNo,
            Date updateTime, String wechatOrigId, String accessToken, String apiTicket,
            Date accessTokenTime, Date apiTicketTime) {
        this.appVersion = appVersion;
        this.appid = appid;
        this.appscret = appscret;
        this.createStaffNo = createStaffNo;
        this.createTime = createTime;
        this.state = state;
        this.tenantName = tenantName;
        this.updateStaffNo = updateStaffNo;
        this.updateTime = updateTime;
        this.wechatOrigId = wechatOrigId;
        this.accessToken = accessToken;
        this.apiTicket = apiTicket;
        this.accessTokenTime = accessTokenTime;
        this.apiTicketTime = apiTicketTime;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)

    @Column(name = "system_id", unique = true, nullable = false)
    public Integer getSystemId() {
        return this.systemId;
    }

    public void setSystemId(Integer systemId) {
        this.systemId = systemId;
    }

    @Column(name = "app_version", length = 8)
    public String getAppVersion() {
        return this.appVersion;
    }

    public void setAppVersion(String appVersion) {
        this.appVersion = appVersion;
    }

    @Column(name = "appid", length = 32)
    public String getAppid() {
        return this.appid;
    }

    public void setAppid(String appid) {
        this.appid = appid;
    }

    @Column(name = "appscret", length = 64)
    public String getAppscret() {
        return this.appscret;
    }

    public void setAppscret(String appscret) {
        this.appscret = appscret;
    }

    @Column(name = "create_staff_no", length = 16)
    public String getCreateStaffNo() {
        return this.createStaffNo;
    }

    public void setCreateStaffNo(String createStaffNo) {
        this.createStaffNo = createStaffNo;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "create_time", nullable = false, length = 19)
    public Date getCreateTime() {
        return this.createTime;
    }

    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    @Column(name = "state")
    public Integer getState() {
        return this.state;
    }

    public void setState(Integer state) {
        this.state = state;
    }

    @Column(name = "tenant_name", length = 64)
    public String getTenantName() {
        return this.tenantName;
    }

    public void setTenantName(String tenantName) {
        this.tenantName = tenantName;
    }

    @Column(name = "update_staff_no", length = 16)
    public String getUpdateStaffNo() {
        return this.updateStaffNo;
    }

    public void setUpdateStaffNo(String updateStaffNo) {
        this.updateStaffNo = updateStaffNo;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "update_time", length = 19)
    public Date getUpdateTime() {
        return this.updateTime;
    }

    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    @Column(name = "wechat_orig_id", length = 32)
    public String getWechatOrigId() {
        return this.wechatOrigId;
    }

    public void setWechatOrigId(String wechatOrigId) {
        this.wechatOrigId = wechatOrigId;
    }

    @Column(name = "access_token")
    public String getAccessToken() {
        return this.accessToken;
    }

    public void setAccessToken(String accessToken) {
        this.accessToken = accessToken;
    }

    @Column(name = "api_ticket")
    public String getApiTicket() {
        return this.apiTicket;
    }

    public void setApiTicket(String apiTicket) {
        this.apiTicket = apiTicket;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "access_token_time", length = 19)
    public Date getAccessTokenTime() {
        return this.accessTokenTime;
    }

    public void setAccessTokenTime(Date accessTokenTime) {
        this.accessTokenTime = accessTokenTime;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "api_ticket_time", length = 19)
    public Date getApiTicketTime() {
        return this.apiTicketTime;
    }

    public void setApiTicketTime(Date apiTicketTime) {
        this.apiTicketTime = apiTicketTime;
    }

}
