package com.eroom.web.entity.po;
// Generated 2017-5-24 16:38:21 by Hibernate Tools 5.2.1.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * SystemStaff generated by hbm2java
 */
@Entity
@Table(name = "system_staff", catalog = "eroom")
public class SystemStaff implements java.io.Serializable {

    private Long staffId;

    private Date chgPwdTime;

    private String createStaffNo;

    private Date createTime;

    private String deptNo;

    private Date endTime;

    private String loginPwd;

    private String mobile;

    private String remark;

    private String staffName;

    private String staffNo;

    private Date startTime;

    private String state;

    private String stationsType;

    private String tenantNo;

    private String updateStaffNo;

    private Date updateTime;

    private Long deptId;

    private Integer serviceNum;

    public SystemStaff() {
    }

    public SystemStaff(String staffNo, Date startTime, String state, String tenantNo) {
        this.staffNo = staffNo;
        this.startTime = startTime;
        this.state = state;
        this.tenantNo = tenantNo;
    }

    public SystemStaff(Date chgPwdTime, String createStaffNo, Date createTime, String deptNo,
            Date endTime, String loginPwd, String mobile, String remark, String staffName,
            String staffNo, Date startTime, String state, String stationsType, String tenantNo,
            String updateStaffNo, Date updateTime, Long deptId, Integer serviceNum) {
        this.chgPwdTime = chgPwdTime;
        this.createStaffNo = createStaffNo;
        this.createTime = createTime;
        this.deptNo = deptNo;
        this.endTime = endTime;
        this.loginPwd = loginPwd;
        this.mobile = mobile;
        this.remark = remark;
        this.staffName = staffName;
        this.staffNo = staffNo;
        this.startTime = startTime;
        this.state = state;
        this.stationsType = stationsType;
        this.tenantNo = tenantNo;
        this.updateStaffNo = updateStaffNo;
        this.updateTime = updateTime;
        this.deptId = deptId;
        this.serviceNum = serviceNum;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)

    @Column(name = "staff_id", unique = true, nullable = false)
    public Long getStaffId() {
        return this.staffId;
    }

    public void setStaffId(Long staffId) {
        this.staffId = staffId;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "chg_pwd_time", length = 19)
    public Date getChgPwdTime() {
        return this.chgPwdTime;
    }

    public void setChgPwdTime(Date chgPwdTime) {
        this.chgPwdTime = chgPwdTime;
    }

    @Column(name = "create_staff_no", length = 16)
    public String getCreateStaffNo() {
        return this.createStaffNo;
    }

    public void setCreateStaffNo(String createStaffNo) {
        this.createStaffNo = createStaffNo;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "create_time", length = 19)
    public Date getCreateTime() {
        return this.createTime;
    }

    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    @Column(name = "dept_no", length = 8)
    public String getDeptNo() {
        return this.deptNo;
    }

    public void setDeptNo(String deptNo) {
        this.deptNo = deptNo;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "end_time", length = 19)
    public Date getEndTime() {
        return this.endTime;
    }

    public void setEndTime(Date endTime) {
        this.endTime = endTime;
    }

    @Column(name = "login_pwd", length = 128)
    public String getLoginPwd() {
        return this.loginPwd;
    }

    public void setLoginPwd(String loginPwd) {
        this.loginPwd = loginPwd;
    }

    @Column(name = "mobile", length = 16)
    public String getMobile() {
        return this.mobile;
    }

    public void setMobile(String mobile) {
        this.mobile = mobile;
    }

    @Column(name = "remark", length = 256)
    public String getRemark() {
        return this.remark;
    }

    public void setRemark(String remark) {
        this.remark = remark;
    }

    @Column(name = "staff_name", length = 32)
    public String getStaffName() {
        return this.staffName;
    }

    public void setStaffName(String staffName) {
        this.staffName = staffName;
    }

    @Column(name = "staff_no", nullable = false, length = 16)
    public String getStaffNo() {
        return this.staffNo;
    }

    public void setStaffNo(String staffNo) {
        this.staffNo = staffNo;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "start_time", nullable = false, length = 19)
    public Date getStartTime() {
        return this.startTime;
    }

    public void setStartTime(Date startTime) {
        this.startTime = startTime;
    }

    @Column(name = "state", nullable = false, length = 4)
    public String getState() {
        return this.state;
    }

    public void setState(String state) {
        this.state = state;
    }

    @Column(name = "stations_type", length = 8)
    public String getStationsType() {
        return this.stationsType;
    }

    public void setStationsType(String stationsType) {
        this.stationsType = stationsType;
    }

    @Column(name = "tenant_no", nullable = false, length = 32)
    public String getTenantNo() {
        return this.tenantNo;
    }

    public void setTenantNo(String tenantNo) {
        this.tenantNo = tenantNo;
    }

    @Column(name = "update_staff_no", length = 16)
    public String getUpdateStaffNo() {
        return this.updateStaffNo;
    }

    public void setUpdateStaffNo(String updateStaffNo) {
        this.updateStaffNo = updateStaffNo;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "update_time", length = 19)
    public Date getUpdateTime() {
        return this.updateTime;
    }

    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    @Column(name = "dept_id")
    public Long getDeptId() {
        return this.deptId;
    }

    public void setDeptId(Long deptId) {
        this.deptId = deptId;
    }

    @Column(name = "service_num")
    public Integer getServiceNum() {
        return this.serviceNum;
    }

    public void setServiceNum(Integer serviceNum) {
        this.serviceNum = serviceNum;
    }

}
