package com.eroom.web.entity.po;
// Generated 2017-5-24 16:38:21 by Hibernate Tools 5.2.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * TRentParam generated by hbm2java
 */
@Entity
@Table(name = "t_rent_param", catalog = "eroom")
public class TRentParam implements java.io.Serializable {

    private Long id;

    private String paramCode;

    private String paramSubType;

    private String paramTitle;

    private String paramType;

    private String parentParamCode;

    private String remark;

    private Integer sortId;

    private String state;

    public TRentParam() {
    }

    public TRentParam(String paramCode, String paramSubType, String paramTitle, String paramType,
            String parentParamCode, String remark, Integer sortId, String state) {
        this.paramCode = paramCode;
        this.paramSubType = paramSubType;
        this.paramTitle = paramTitle;
        this.paramType = paramType;
        this.parentParamCode = parentParamCode;
        this.remark = remark;
        this.sortId = sortId;
        this.state = state;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)

    @Column(name = "id", unique = true, nullable = false)
    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    @Column(name = "param_code", length = 32)
    public String getParamCode() {
        return this.paramCode;
    }

    public void setParamCode(String paramCode) {
        this.paramCode = paramCode;
    }

    @Column(name = "param_sub_type", length = 32)
    public String getParamSubType() {
        return this.paramSubType;
    }

    public void setParamSubType(String paramSubType) {
        this.paramSubType = paramSubType;
    }

    @Column(name = "param_title", length = 64)
    public String getParamTitle() {
        return this.paramTitle;
    }

    public void setParamTitle(String paramTitle) {
        this.paramTitle = paramTitle;
    }

    @Column(name = "param_type", length = 32)
    public String getParamType() {
        return this.paramType;
    }

    public void setParamType(String paramType) {
        this.paramType = paramType;
    }

    @Column(name = "parent_param_code", length = 32)
    public String getParentParamCode() {
        return this.parentParamCode;
    }

    public void setParentParamCode(String parentParamCode) {
        this.parentParamCode = parentParamCode;
    }

    @Column(name = "remark", length = 128)
    public String getRemark() {
        return this.remark;
    }

    public void setRemark(String remark) {
        this.remark = remark;
    }

    @Column(name = "sort_id")
    public Integer getSortId() {
        return this.sortId;
    }

    public void setSortId(Integer sortId) {
        this.sortId = sortId;
    }

    @Column(name = "state", length = 4)
    public String getState() {
        return this.state;
    }

    public void setState(String state) {
        this.state = state;
    }

}
