package com.eroom.web.entity.po;
// Generated 2017-5-24 16:38:21 by Hibernate Tools 5.2.1.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TRoomBook generated by hbm2java
 */
@Entity
@Table(name = "t_room_book", catalog = "eroom")
public class TRoomBook implements java.io.Serializable {

    private Long bookId;

    private long rentId;

    private long custRenterId;

    private long custOwnerId;

    private long roomId;

    private Long bedRoomId;

    private Date startTime;

    private Date endTime;

    private String state;

    private String applyState;

    private Date createTime;

    private Date updateTime;

    private String remark;

    public TRoomBook() {
    }

    public TRoomBook(long rentId, long custRenterId, long custOwnerId, long roomId, String state,
            String applyState, Date createTime) {
        this.rentId = rentId;
        this.custRenterId = custRenterId;
        this.custOwnerId = custOwnerId;
        this.roomId = roomId;
        this.state = state;
        this.applyState = applyState;
        this.createTime = createTime;
    }

    public TRoomBook(long rentId, long custRenterId, long custOwnerId, long roomId, Long bedRoomId,
            Date startTime, Date endTime, String state, String applyState, Date createTime,
            Date updateTime, String remark) {
        this.rentId = rentId;
        this.custRenterId = custRenterId;
        this.custOwnerId = custOwnerId;
        this.roomId = roomId;
        this.bedRoomId = bedRoomId;
        this.startTime = startTime;
        this.endTime = endTime;
        this.state = state;
        this.applyState = applyState;
        this.createTime = createTime;
        this.updateTime = updateTime;
        this.remark = remark;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)

    @Column(name = "book_id", unique = true, nullable = false)
    public Long getBookId() {
        return this.bookId;
    }

    public void setBookId(Long bookId) {
        this.bookId = bookId;
    }

    @Column(name = "rent_id", nullable = false)
    public long getRentId() {
        return this.rentId;
    }

    public void setRentId(long rentId) {
        this.rentId = rentId;
    }

    @Column(name = "cust_renter_id", nullable = false)
    public long getCustRenterId() {
        return this.custRenterId;
    }

    public void setCustRenterId(long custRenterId) {
        this.custRenterId = custRenterId;
    }

    @Column(name = "cust_owner_id", nullable = false)
    public long getCustOwnerId() {
        return this.custOwnerId;
    }

    public void setCustOwnerId(long custOwnerId) {
        this.custOwnerId = custOwnerId;
    }

    @Column(name = "room_id", nullable = false)
    public long getRoomId() {
        return this.roomId;
    }

    public void setRoomId(long roomId) {
        this.roomId = roomId;
    }

    @Column(name = "bed_room_id")
    public Long getBedRoomId() {
        return this.bedRoomId;
    }

    public void setBedRoomId(Long bedRoomId) {
        this.bedRoomId = bedRoomId;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "start_time", length = 19)
    public Date getStartTime() {
        return this.startTime;
    }

    public void setStartTime(Date startTime) {
        this.startTime = startTime;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "end_time", length = 19)
    public Date getEndTime() {
        return this.endTime;
    }

    public void setEndTime(Date endTime) {
        this.endTime = endTime;
    }

    @Column(name = "state", nullable = false, length = 4)
    public String getState() {
        return this.state;
    }

    public void setState(String state) {
        this.state = state;
    }

    @Column(name = "apply_state", nullable = false, length = 4)
    public String getApplyState() {
        return this.applyState;
    }

    public void setApplyState(String applyState) {
        this.applyState = applyState;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "create_time", nullable = false, length = 19)
    public Date getCreateTime() {
        return this.createTime;
    }

    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "update_time", length = 19)
    public Date getUpdateTime() {
        return this.updateTime;
    }

    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    @Column(name = "remark")
    public String getRemark() {
        return this.remark;
    }

    public void setRemark(String remark) {
        this.remark = remark;
    }

}
