package com.eroom.web.entity.po;
// Generated 2017-5-24 16:38:21 by Hibernate Tools 5.2.1.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TRoomInfo generated by hbm2java
 */
@Entity
@Table(name = "t_room_info", catalog = "eroom")
public class TRoomInfo implements java.io.Serializable {

    private Long roomId;

    private String name;

    private String roomType;

    private String floor;

    private String imageUrl;

    private String environment;

    private String year;

    private String buildType;

    private String heating;

    private String greening;

    private String config;

    private String state;

    private Date updateTime;

    private Date createTime;

    private String aroundInfo;

    private String traffice;

    private String remark;

    public TRoomInfo() {
    }

    public TRoomInfo(String state, Date createTime) {
        this.state = state;
        this.createTime = createTime;
    }

    public TRoomInfo(String name, String roomType, String floor, String imageUrl,
            String environment, String year, String buildType, String heating, String greening,
            String config, String state, Date updateTime, Date createTime, String aroundInfo,
            String traffice, String remark) {
        this.name = name;
        this.roomType = roomType;
        this.floor = floor;
        this.imageUrl = imageUrl;
        this.environment = environment;
        this.year = year;
        this.buildType = buildType;
        this.heating = heating;
        this.greening = greening;
        this.config = config;
        this.state = state;
        this.updateTime = updateTime;
        this.createTime = createTime;
        this.aroundInfo = aroundInfo;
        this.traffice = traffice;
        this.remark = remark;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)

    @Column(name = "room_id", unique = true, nullable = false)
    public Long getRoomId() {
        return this.roomId;
    }

    public void setRoomId(Long roomId) {
        this.roomId = roomId;
    }

    @Column(name = "name", length = 16)
    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    @Column(name = "room_type", length = 32)
    public String getRoomType() {
        return this.roomType;
    }

    public void setRoomType(String roomType) {
        this.roomType = roomType;
    }

    @Column(name = "floor", length = 8)
    public String getFloor() {
        return this.floor;
    }

    public void setFloor(String floor) {
        this.floor = floor;
    }

    @Column(name = "image_url")
    public String getImageUrl() {
        return this.imageUrl;
    }

    public void setImageUrl(String imageUrl) {
        this.imageUrl = imageUrl;
    }

    @Column(name = "environment", length = 8)
    public String getEnvironment() {
        return this.environment;
    }

    public void setEnvironment(String environment) {
        this.environment = environment;
    }

    @Column(name = "year", length = 8)
    public String getYear() {
        return this.year;
    }

    public void setYear(String year) {
        this.year = year;
    }

    @Column(name = "build_type", length = 8)
    public String getBuildType() {
        return this.buildType;
    }

    public void setBuildType(String buildType) {
        this.buildType = buildType;
    }

    @Column(name = "heating", length = 8)
    public String getHeating() {
        return this.heating;
    }

    public void setHeating(String heating) {
        this.heating = heating;
    }

    @Column(name = "greening", length = 8)
    public String getGreening() {
        return this.greening;
    }

    public void setGreening(String greening) {
        this.greening = greening;
    }

    @Column(name = "config", length = 128)
    public String getConfig() {
        return this.config;
    }

    public void setConfig(String config) {
        this.config = config;
    }

    @Column(name = "state", nullable = false, length = 8)
    public String getState() {
        return this.state;
    }

    public void setState(String state) {
        this.state = state;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "update_time", length = 19)
    public Date getUpdateTime() {
        return this.updateTime;
    }

    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "create_time", nullable = false, length = 19)
    public Date getCreateTime() {
        return this.createTime;
    }

    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    @Column(name = "around_info", length = 128)
    public String getAroundInfo() {
        return this.aroundInfo;
    }

    public void setAroundInfo(String aroundInfo) {
        this.aroundInfo = aroundInfo;
    }

    @Column(name = "traffice", length = 128)
    public String getTraffice() {
        return this.traffice;
    }

    public void setTraffice(String traffice) {
        this.traffice = traffice;
    }

    @Column(name = "remark", length = 128)
    public String getRemark() {
        return this.remark;
    }

    public void setRemark(String remark) {
        this.remark = remark;
    }

}
