package com.eroom.web.entity.po;
// Generated 2017-5-24 16:38:21 by Hibernate Tools 5.2.1.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * WechatNoticeTemplet generated by hbm2java
 */
@Entity
@Table(name = "wechat_notice_templet", catalog = "eroom")
public class WechatNoticeTemplet implements java.io.Serializable {

    private Long templetId;

    private Date createTime;

    private String remark;

    private int state;

    private String templetCode;

    private String templetTitle;

    private String templetType;

    private String tenantNo;

    public WechatNoticeTemplet() {
    }

    public WechatNoticeTemplet(int state, String templetCode, String templetTitle,
            String templetType, String tenantNo) {
        this.state = state;
        this.templetCode = templetCode;
        this.templetTitle = templetTitle;
        this.templetType = templetType;
        this.tenantNo = tenantNo;
    }

    public WechatNoticeTemplet(Date createTime, String remark, int state, String templetCode,
            String templetTitle, String templetType, String tenantNo) {
        this.createTime = createTime;
        this.remark = remark;
        this.state = state;
        this.templetCode = templetCode;
        this.templetTitle = templetTitle;
        this.templetType = templetType;
        this.tenantNo = tenantNo;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)

    @Column(name = "templet_id", unique = true, nullable = false)
    public Long getTempletId() {
        return this.templetId;
    }

    public void setTempletId(Long templetId) {
        this.templetId = templetId;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "create_time", length = 19)
    public Date getCreateTime() {
        return this.createTime;
    }

    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    @Column(name = "remark", length = 256)
    public String getRemark() {
        return this.remark;
    }

    public void setRemark(String remark) {
        this.remark = remark;
    }

    @Column(name = "state", nullable = false)
    public int getState() {
        return this.state;
    }

    public void setState(int state) {
        this.state = state;
    }

    @Column(name = "templet_code", nullable = false, length = 128)
    public String getTempletCode() {
        return this.templetCode;
    }

    public void setTempletCode(String templetCode) {
        this.templetCode = templetCode;
    }

    @Column(name = "templet_title", nullable = false, length = 64)
    public String getTempletTitle() {
        return this.templetTitle;
    }

    public void setTempletTitle(String templetTitle) {
        this.templetTitle = templetTitle;
    }

    @Column(name = "templet_type", nullable = false, length = 8)
    public String getTempletType() {
        return this.templetType;
    }

    public void setTempletType(String templetType) {
        this.templetType = templetType;
    }

    @Column(name = "tenant_no", nullable = false, length = 32)
    public String getTenantNo() {
        return this.tenantNo;
    }

    public void setTenantNo(String tenantNo) {
        this.tenantNo = tenantNo;
    }

}
