package com.eroom.web.entity.po;
// Generated 2017-5-24 16:38:21 by Hibernate Tools 5.2.1.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * WechatNotice generated by hbm2java
 */
@Entity
@Table(name = "wechat_notice", catalog = "eroom")
public class WechatNotice implements java.io.Serializable {

    private Long noticeId;

    private Date createTime;

    private String noticeContent;

    private String openid;

    private String remark;

    private Date sendTime;

    private int state;

    private String templetCode;

    private long templetId;

    private String tenantNo;

    private Date updateTime;

    public WechatNotice() {
    }

    public WechatNotice(String noticeContent, String openid, Date sendTime, int state,
            String templetCode, long templetId, String tenantNo) {
        this.noticeContent = noticeContent;
        this.openid = openid;
        this.sendTime = sendTime;
        this.state = state;
        this.templetCode = templetCode;
        this.templetId = templetId;
        this.tenantNo = tenantNo;
    }

    public WechatNotice(Date createTime, String noticeContent, String openid, String remark,
            Date sendTime, int state, String templetCode, long templetId, String tenantNo,
            Date updateTime) {
        this.createTime = createTime;
        this.noticeContent = noticeContent;
        this.openid = openid;
        this.remark = remark;
        this.sendTime = sendTime;
        this.state = state;
        this.templetCode = templetCode;
        this.templetId = templetId;
        this.tenantNo = tenantNo;
        this.updateTime = updateTime;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)

    @Column(name = "notice_id", unique = true, nullable = false)
    public Long getNoticeId() {
        return this.noticeId;
    }

    public void setNoticeId(Long noticeId) {
        this.noticeId = noticeId;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "create_time", length = 19)
    public Date getCreateTime() {
        return this.createTime;
    }

    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    @Column(name = "notice_content", nullable = false, length = 512)
    public String getNoticeContent() {
        return this.noticeContent;
    }

    public void setNoticeContent(String noticeContent) {
        this.noticeContent = noticeContent;
    }

    @Column(name = "openid", nullable = false, length = 64)
    public String getOpenid() {
        return this.openid;
    }

    public void setOpenid(String openid) {
        this.openid = openid;
    }

    @Column(name = "remark", length = 256)
    public String getRemark() {
        return this.remark;
    }

    public void setRemark(String remark) {
        this.remark = remark;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "send_time", nullable = false, length = 19)
    public Date getSendTime() {
        return this.sendTime;
    }

    public void setSendTime(Date sendTime) {
        this.sendTime = sendTime;
    }

    @Column(name = "state", nullable = false)
    public int getState() {
        return this.state;
    }

    public void setState(int state) {
        this.state = state;
    }

    @Column(name = "templet_code", nullable = false, length = 128)
    public String getTempletCode() {
        return this.templetCode;
    }

    public void setTempletCode(String templetCode) {
        this.templetCode = templetCode;
    }

    @Column(name = "templet_id", nullable = false)
    public long getTempletId() {
        return this.templetId;
    }

    public void setTempletId(long templetId) {
        this.templetId = templetId;
    }

    @Column(name = "tenant_no", nullable = false, length = 32)
    public String getTenantNo() {
        return this.tenantNo;
    }

    public void setTenantNo(String tenantNo) {
        this.tenantNo = tenantNo;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "update_time", length = 19)
    public Date getUpdateTime() {
        return this.updateTime;
    }

    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

}
